// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWqTPoz-YnVu3oSaP2RyAJ_jfeeM08M_k',
    appId: '1:537771971328:web:55a6888bec0da245a159e5',
    messagingSenderId: '537771971328',
    projectId: 'crudapp-df2b8',
    authDomain: 'crudapp-df2b8.firebaseapp.com',
    storageBucket: 'crudapp-df2b8.appspot.com',
    measurementId: 'G-M8E1N6FW8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuoSv2lZx2oNf_rIiN2SfvmOPIVJ_rybI',
    appId: '1:537771971328:android:b8bf5eced29d7b95a159e5',
    messagingSenderId: '537771971328',
    projectId: 'crudapp-df2b8',
    storageBucket: 'crudapp-df2b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7yq5zOvsWORD8lxcwASEBOHr-0APKQVE',
    appId: '1:537771971328:ios:3ec2dae3a46681b3a159e5',
    messagingSenderId: '537771971328',
    projectId: 'crudapp-df2b8',
    storageBucket: 'crudapp-df2b8.appspot.com',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7yq5zOvsWORD8lxcwASEBOHr-0APKQVE',
    appId: '1:537771971328:ios:7b3f6b0460912022a159e5',
    messagingSenderId: '537771971328',
    projectId: 'crudapp-df2b8',
    storageBucket: 'crudapp-df2b8.appspot.com',
    iosBundleId: 'com.example.flutterToDoList.RunnerTests',
  );
}
